name             'test_cookbook_3'
maintainer       'Muriel Salvan'
maintainer_email 'muriel@x-aeon.com'
supports         'debian'
chef_version     '>= 14.8'
source_url       'https://x-aeon.com'
issues_url       'https://x-aeon.com'
license          'BSD'
description      'Installs/Configures test_cookbook_3'
long_description ''
version          '0.1.0'
depends          'test_cookbook_4'
depends          'test_cookbook_5'
